chg: $0 replaced by $script_name

diff --git a/bin/install_updates b/bin/install_updates
--- a/bin/install_updates
+++ b/bin/install_updates
@@ -6,6 +6,7 @@
 #     install_updates [DIRECTORY] [CONFIG]
 #
 
+script_name="$(basename $0)"
 config_name="version.conf"
 updates_name="update_scripts"
 
@@ -30,7 +31,7 @@ fi
 # Error if updates directory not found
 if [ ! -d "$updates_dir" ]; then
     [ -z $updates_dir ] && unset $updates_dir
-    >&2 echo "$0: Cannot load ${updates_dir:=$updates_name}: directory does not exist."
+    >&2 echo "${script_name}: Cannot load ${updates_dir:=$updates_name}: directory does not exist."
     exit 1
 fi
 
@@ -51,7 +52,7 @@ install_updates=($(
     elif [ ! -f $config_file ]; then
         echo "${updates[@]}"
     else
-        >&2 echo "$0: Current version file \"$cur_update\" does found in $updates_dir"
+        >&2 echo "${script_name}: Current version file \"$cur_update\" does found in $updates_dir"
         exit 1
     fi
 ))
diff --git a/bin/load_dirs b/bin/load_dirs
--- a/bin/load_dirs
+++ b/bin/load_dirs
@@ -11,6 +11,7 @@ print_spaces() {
     eval 'printf "%0.s " {1..'$spaces_count'}'
 }
 
+script_name="$(basename $0)"
 config_name="load_dirs.conf"
 
 # Checking config
@@ -24,7 +25,7 @@ fi
 
 # Error if config not found
 if [ ! -f "$config_file" ]; then
-    >&2 echo "$0: Cannot load ${config_file:=$config_name}: file does not exist."
+    >&2 echo "${script_name}: Cannot load ${config_file:=$config_name}: file does not exist."
     exit 1
 fi
 
@@ -55,13 +56,14 @@ for storage in "${VOLUMES[@]}"; do
            echo -n '(copy) '
            cp -Lrp $dir ${newdir} || exit 1
        fi
+
        echo -n '(link) '
 
        # If $dir is symbolyc link
        if [ -L $dir ]; then
            linkdir="$(readlink $dir)"
            if [ "$linkdir" = "$newdir" ]; then
-               >&2 echo '$0: duplicate dirname!'
+               >&2 echo "${script_name}: duplicate name!"
                exit 1
            else
                rm -rf $linkdir
diff --git a/bin/load_envs b/bin/load_envs
--- a/bin/load_envs
+++ b/bin/load_envs
@@ -10,12 +10,13 @@ chk_env() {
     eval env="\$$1"
     val="${env:-$2}"
     if [ -z "$val" ]; then
-        >&2 echo "$0: Enviroment vaiable \$$1 is not set."
+        >&2 echo "${script_name}: Enviroment vaiable \$$1 is not set."
         exit 1
     fi  
     export "$1"="$val"
 }
 
+script_name="$(basename $0)"
 config_name="load_envs.conf"
 prefix="DEFAULT_"
 
@@ -30,7 +31,7 @@ fi
 
 # Error if config not found
 if [ ! -f "$config_file" ]; then
-    >&2 echo "$0: Cannot load ${config_file:=$config_name}: file does not exist."
+    >&2 echo ${script_name}": Cannot load ${config_file:=$config_name}: file does not exist."
     exit 1
 fi
 
diff --git a/bin/load_services b/bin/load_services
--- a/bin/load_services
+++ b/bin/load_services
@@ -6,6 +6,7 @@
 #     load_services [DIRECTORY] [CONFIG]
 #
 
+script_name="$(basename $0)"
 config_name="supervisord.conf"
 config_path="/etc/supervisor/conf.d"
 services_name="services"
@@ -32,7 +33,7 @@ fi
 if [ ! -d $config_file ]; then
     touch $config_file || exit 1
 else
-    >&2 echo "$0: Error $config_file is directory."
+    >&2 echo "${script_name}: Error $config_file is directory."
 exit 1
 fi
 
@@ -46,7 +47,7 @@ EOT
 # Error if services directory not found
 if [ ! -d "$services_dir" ]; then
     [ -z $services_dir ] && unset $services_dir
-    >&2 echo "$0: Cannot load ${services_dir:=$services_name}: directory does not exist."
+    >&2 echo "${script_name}: Cannot load ${services_dir:=$services_name}: directory does not exist."
     exit 1
 fi
 
@@ -57,19 +58,19 @@ for service_var in ${services[@],,} ; do
     service_name=$(ls $services_dir -1 | grep -iP "$service_mask")
 
     if $(echo $service_name | grep -q ' '); then
-        >&2 echo "$0: Duplicate services: $(echo $service_name)"
+        >&2 echo "${script_name}: Duplicate services: $(echo $service_name)"
         exit 1
     fi
 
     if [ -z "$service_name" ]; then
-        >&2 echo "$0: Service $service_var not found in $services_dir"
+        >&2 echo "${script_name}: Service $service_var not found in $services_dir"
         exit 1
     fi
 
     service_runit="$services_dir/$service_name/$service_name.runit"
 
     if [ ! -f $service_runit ]; then
-        >&2 echo "$0: File $service_var.runit not found in $services_dir/$service_name/"
+        >&2 echo "${script_name}: File $service_var.runit not found in $services_dir/$service_name/"
         exit 1
     fi
 
