add: errors checks

diff --git a/bin/load_services b/bin/load_services
--- a/bin/load_services
+++ b/bin/load_services
@@ -6,20 +6,45 @@
 #     load_services [DIRECTORY]
 #
 
-config_name="services"
+services_name="services"
 
 # Checking config
 if [ ! -z $1 ]; then
-    config_dir="$1"
-elif [ -d $config_name ]; then
-    config_dir="$config_name"
-elif [ -d /etc/$config_name ]; then
-    config_dir="/etc/$config_name"
+    services_dir="$1"
+elif [ -d $services_name ]; then
+    services_dir="$services_name"
+elif [ -d /etc/$services_name ]; then
+    services_dir="/etc/$services_name"
 fi
 
 # Error if config not found
-if [ ! -d "$config_dir" ]; then
-    [ -z $config_dir ] && unset $config_dir
-    >&2 echo "$0: Cannot load ${config_dir:=$config_name}: directory does not exist."
+if [ ! -d "$services_dir" ]; then
+    [ -z $services_dir ] && unset $services_dir
+    >&2 echo "$0: Cannot load ${services_dir:=$services_name}: directory does not exist."
     exit 1
 fi
+
+services=($(env | grep -oP '(?<=^SERVICE_)[a-zA-Z0-9_]*(?==(?i:true|1))'))
+
+for service_var in ${services[@],,} ; do
+    service_mask=$(echo $service_var | sed 's/_/.?/g')
+    service_name=$(ls $services_dir -1 | grep -iP "$service_mask")
+
+    if $(echo $service_name | grep -q ' '); then
+        >&2 echo "$0: Duplicate services: $(echo $service_name)"
+        exit 1
+    fi
+
+    if [ -z "$service_name" ]; then
+        >&2 echo "$0: Service $service_var not found in $services_dir"
+        exit 1
+    fi
+
+    service_runit="$services_dir/$service_name/$service_name.runit"
+
+    if [ ! -f $service_runit ]; then
+        >&2 echo "$0: File $service_var.runit not found in $services_dir/$service_name/"
+        exit 1
+    fi
+
+done
